plugins {
    id 'java'
    id 'org.springframework.boot' version "${SPRING_BOOT_VERSION}"
    id 'io.spring.dependency-management' version "${SPRING_BOOT_DEPENDENCY_MANAGEMENT_VERSION}"
    id "org.asciidoctor.jvm.convert" version "3.3.2"
}

group = 'com.nextdaydelivery'
version = '0.0.1-SNAPSHOT'
description = 'delivery-backend'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(Integer.parseInt(JAVA_VERSION))
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
    asciidoctorExt
}

repositories {
    mavenCentral()
}

dependencies {
    // Spring
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // QueryDSL
    implementation "io.github.openfeign.querydsl:querydsl-core:${QUERYDSL_VERSION}"
    implementation "io.github.openfeign.querydsl:querydsl-jpa:${QUERYDSL_VERSION}"

    annotationProcessor "io.github.openfeign.querydsl:querydsl-apt:${QUERYDSL_VERSION}:jakarta"

    annotationProcessor "jakarta.annotation:jakarta.annotation-api"
    annotationProcessor "jakarta.persistence:jakarta.persistence-api"

    // PostgreSQL
    runtimeOnly 'org.postgresql:postgresql'

    // Liquibase
    implementation 'org.liquibase:liquibase-core'

    // JJWT
    implementation "io.jsonwebtoken:jjwt-api:${JJWT_VERSION}"
    runtimeOnly "io.jsonwebtoken:jjwt-impl:${JJWT_VERSION}"
    runtimeOnly "io.jsonwebtoken:jjwt-jackson:${JJWT_VERSION}"

    // ai
    implementation "com.google.genai:google-genai:${GENAI_VERSION}"

    //rest docs
    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
    asciidoctorExt 'org.springframework.restdocs:spring-restdocs-asciidoctor'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'com.h2database:h2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'com.h2database:h2'
}

// REST DOCS SETTING
ext {
    snippetsDir = file('build/generated-snippets')
}

tasks.named('test') {
    useJUnitPlatform()
    outputs.dir snippetsDir
}

tasks.named('asciidoctor') {
    inputs.dir snippetsDir
    configurations 'asciidoctorExt'
    dependsOn tasks.test
}

bootJar {
    dependsOn tasks.asciidoctor
    from ("${asciidoctor.outputDir}") {
        into 'static/docs'
    }
}

bootRun {
    dependsOn tasks.asciidoctor
    classpath += files(tasks.asciidoctor.outputDir)

    systemProperty "spring.web.resources.static-locations",
            "classpath:/static/,file:${tasks.asciidoctor.outputDir}"
}