name: Develop CI

on:
  push:
    branches:
      - develop
      - chore/39-cicd-test
  pull_request:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 테스트 복구 전까지 임시
      - name: Build jar
        run: ./gradlew clean bootJar -x test

      - name: Build Docker image
        run: docker build -t next-day-delivery-api:dev .